<?php

namespace App\PssWorkerBundle\Repository;

/**
 * SyncLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyncLogRepository extends \Doctrine\ORM\EntityRepository
{
}
